# Generated by Django 4.2.8 on 2023-12-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('problem', models.TextField()),
                ('level', models.TextField()),
                ('type', models.TextField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5')])),
                ('solution', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
