# Generated by Django 4.2.8 on 2024-01-29 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('problem', models.TextField()),
                ('level', models.TextField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5')])),
                ('type', models.TextField()),
                ('solution', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=models.SET('anonymous'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(max_length=150)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathtrainer.studyplan')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathtrainer.problem')),
            ],
        ),
    ]
