# Generated by Django 4.2.8 on 2023-12-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathtrainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathtrainer.problem')),
            ],
        ),
    ]
