# Generated by Django 4.2.8 on 2024-01-30 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathtrainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='StudyPlan',
            new_name='Flow',
        ),
        migrations.DeleteModel(
            name='StudyPlanSection',
        ),
        migrations.AddField(
            model_name='flowsection',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathtrainer.flow'),
        ),
    ]
